#!/bin/bash

# This code was Copy-Pasted from
# https://anxiousmofo.wordpress.com/2008/08/04/opening-files-in-an-already-running-instance-of-emacs/

if test -n "$1"; then
    emacsclient --no-wait "$@" 2> /dev/null || emacs "$@" &
else
    emacsclient --eval "(raise-frame (selected-frame))" 2> /dev/null || emacs &
fi
