#!/bin/bash

DEVICE_NAME=$(jmtpfs -l 2>&1 | while read line; do
	if [[ $line == Device* ]]; then 
		echo $line | 
		sed 's/Device[^\n]*\ is\ a\ //g' | 
		sed 's/([^)]*)//g' | 
		sed 's/\([0-9]\/\)*[0-9]*//g' | 
		sed 's/\//_/g' | 
		sed 's/\.//g' | 
		sed 's/ *$//g' | 
		sed 's/ /_/g' |
		sed 's/__*/_/g'
	fi	
done)

if [ "$DEVICE_NAME" ]; then
	echo $DEVICE_NAME
else
	echo "Android"
fi